try:   
    print(x)
except:
    print("Algo salio mal")
finally:
    print("El try ha finalizado")